### ISSUE TITLE
log  error  

### ISSUE THREAD

**Issue by OSMeteor** [holdno/firetower#2]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xff3ee4]

goroutine 696 [running]:
github.com/holdno/firetower/service/gateway.fireLog(0x0, 0x17bb3ba, 0x5, 0xc000ffc360, 0x2a)
        C:/GOPATH/src/github.com/holdno/firetower/service/gateway/log.go:65 +0x5a4
github.com/holdno/firetower/service/gateway.(*FireInfo).Panic(0x0, 0xc000ffc360, 0x2a)
        C:/GOPATH/src/github.com/holdno/firetower/service/gateway/tower.go:71 +0x62
github.com/holdno/firetower/service/gateway.(*FireTower).readDispose(0xc0015ca340)
        C:/GOPATH/src/github.com/holdno/firetower/service/gateway/tower.go:370 +0x59e
created by github.com/holdno/firetower/service/gateway.(*FireTower).Run
        C:/GOPATH/src/github.com/holdno/firetower/service/gateway/tower.go:192 +0x8f

**Comment by OSMeteor** [comment]
panic: runtime error: invalid memory address or nil pointer dereference [signal 0xc0000005 code=0x0 addr=0x0 pc=0xff3f48]  goroutine 2558 [running]: github.com/holdno/firetower/service/gateway.NewFireInfo(0xc001847110, 0xc001ff3bd0, 0x12)         C:/GOPATH/src/github.com/holdno/firetower/service/gateway/tower.go:57 +0x58 portalBackendApi/controllers.(*WebSocketController).Get.func4(0xc001ff3bd0, 0xc00211f0d0, 0x1, 0x1, 0xc00211f0d0)         C:/GOPATH/src/portalBackendApi/controllers/WebSocket.go:207 +0x2d8 github.com/holdno/firetower/service/gateway.(*FireTower).readDispose(0xc001847110)         C:/GOPATH/src/github.com/holdno/firetower/service/gateway/tower.go:395 +0x358 created by github.com/holdno/firetower/service/gateway.(*FireTower).Run         C:/GOPATH/src/github.com/holdno/firetower/service/gateway/tower.go:192 +0x8f

**Comment by holdno** [comment]
是否对`firePool`有做了修改呢？

**Comment by OSMeteor** [comment]
> 是否对service/gateway/tower.go中的`firePool`有做了修改呢？

 service\gateway
 
fixed this 
```
func NewFireInfo(t *FireTower, context *FireLife) *FireInfo {
	fireInfo := firePool.Get().(*FireInfo)
	if context != nil {
	  if(fireInfo!=nil && fireInfo.Context!=nil){
      fireInfo.Context = context
   	}else {
      return fireInfo
    }
	} else {
		fireInfo.Context.reset(t)
	}
	return fireInfo
}
```
